version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial_db
    command: >
      postgres -c wal_level=logical
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      tricao_network:

  debezium:
    image: debezium/connect:2.4
    container_name: debezium
    restart: always
    depends_on:
      - broker
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
    volumes:
      - debezium_connectors:/kafka/connect
    networks:
      tricao_network:

  debezium-ui:
    image: debezium/debezium-ui:2.4
    container_name: debezium-ui
    restart: always
    depends_on:
      - debezium
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONNECT_URIS: http://debezium:8083
    networks:
      tricao_network:

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      tricao_network:

  broker:
    image: confluentinc/cp-server
    container_name: broker
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      tricao_network:

  schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry
    restart: always
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    networks:
      tricao_network:

  control-center:
    image: confluentinc/cp-enterprise-control-center
    container_name: control-center
    restart: always
    depends_on:
      - broker
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker:29092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    networks:
      tricao_network:

volumes:
  postgres_data:
  debezium_connectors:
  kafka_data:

networks:
  tricao_network:
